services:
  - type: web
    name: gnss-app-api
    env: node
    buildCommand: npm install && npm run build:server
    startCommand: node dist/server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production

  - type: static
    name: gnss-app-client
    buildCommand: npm run build:client
    staticPublishPath: dist/client
    routes:
      - type: rewrite
        source: /*
        destination: /index.html